language: python
dist: "xenial"
sudo: true
addons:
  apt:
    packages:
      - libhdf5-dev
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install pytest coveralls pytest-cov
- pip install .
script:
- pytest --cov=viresclient
after_success:
- coveralls
